name: Deliver container and run tests

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    name: Deliver container and run tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/apidev-eindproject:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/apidev-eindproject:latest

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest -vv test_xmas_presents.py
